### ISSUE TITLE
Horizontal Scroll in mobile view

### ISSUE THREAD

**Issue by jiseeeh** [pangilinanervin22/philippine-blog#3]
![Screenshot_2022-05-18-10-23-46-77_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/80168125/168944605-75f90cb3-2484-4644-a02a-331dcf49e667.jpg)

**Comment by jiseeeh** [comment]
This can be **temporarily** solved by scrolling up to the bottom.

 _At least on my end._ :>

**Comment by pangilinanervin22** [comment]
Thank you for your concern, I accidentally assign a large pixels size in fact section that's why it overlap the entire body now I successfully resolve the issue
